WIP: Rust rewrite of wordlistctl
BlackArch/wordlistctl pull request #32
Opened 2024-03-28 13:15 UTC by Sable-20

## Complete rewrite of `wordlistctl`

This is a completely rust based rewrite of `wordlistctl`.

Original authors left in `Cargo.toml` as "blackarch" with me (the main contributor) written in separately. 

The goal of this rewrite is to improve the speed of `wordlistctl` and implement any missing features or fix existing issues.

This will also improve code readability through Rust's strict type system along with strict formatting rules enforced by `rustfmt` and the linters being run. Code security is also paramount and has a workflow specifically for managing code security. 

Manpage generation will also because automatic so that it can be automated and consistent.

Roadmap:

- [ ] Document existing structs and enums that involve cli options
- [ ] Write contribution convention and instruction file
- [ ] Eventually remove repo.json after ensuring all data is 
- [ ] Document all functions
- [ ] Integrate cargo doc function and manpage (using [`clap_mangen`](https://crates.io/crates/clap_mangen) ) generation into artifact generation **OR** pre-commit hooks
- [ ] Finish adding all commands
- [ ] Implement command matching
- [ ] Add functions
- [ ] Implement multithreading and retrieving files as chunked data maybe via `rayon` and its `par_iter` style, considering using `Tokio` instead of `rayon`
- [ ] Implement custom error types 
- [ ] More... (cannot write right now)

2024-03-28 15:04 UTC, Sable-20 commented
_**NOTE:**_ in case it wasn't clear in the original comment, don't merge this yet it is a breaking change and the tool will not work until everything is fully implemented, this is merely to track the progress in reference to the main repository, there is much to be done and there will be likely be breaking changes.

We are still only on version `0.10.0-alpha.1.4.0`

2024-04-02 13:17 UTC, Sable-20 commented
Fetching is currently supported for search by name and search by name with the regex flag as suggested in #30 

Flag for regex searching is `-r` or `--regex`, like #30 addressed, `-r` is false by default but when true allows for searching by substring matching, in this case using the `regex` crate in Rust.

Decompression is not yet implemented however it is currently being investigated, there is allegedly features with signatures such as:
```rust
pub fn gzip(self, enable: bool) -> ClientBuilder
```

and others that decompress things like `brotli` files

More importantly there is the option
```rust
pub fun deflate(self, enable: bool) -> ClientBuilder
```

Which may handle all compressed types, documentation is light so I will be looking into this more. To be conservative I will enable `gzip`, `brotli`, and `deflate` until further testing can be done.

2024-04-02 17:01 UTC, Sable-20 commented
Deflate, gzip, and brotli does compile and pass all actions on [rwordlistctl](https://github.com/Sable-20/rwordlistctl), including: 
1. Rust compile and test workflow
2. linter
3. Codacy security scan.

2024-04-08 13:40 UTC, Sable-20 commented
Bugs with decompression fixed, now all files in the wordlists can properly decompress.

The main issue was `.tar.gz` files would not properly decompress due to the way that `reqwest` processes files. The fix was to regex match the end of the url to get the file type and manually decompress using `flate2`.

2024-04-09 01:25 UTC, Sable-20 commented
A low of work has gone into this and we're almost there, we have to review the `search` and `list` options because while rewriting it feels almost redundant and it's possible to either merge them or do away with one of them.

Like I stated in my commit I'm going to do a proper code review because it is late and I may just be a bit crazy right now!

2024-04-11 17:47 UTC, Sable-20 commented
As of the most recent commit (https://github.com/Sable-20/rwordlistctl/commit/75203525fa8d040dc8b69252980929a84169cb62) my rewrite has begun it's migration away from Docker towards Nix for reproducible dev environments as well as build environments

2024-04-17 00:26 UTC, Sable-20 commented
It essentially works

I'd like to ask for a review and for feedback on the idea from a maintainer, sorry for the highlight but @dualfade you're the only maintainer I happen to have noticed from the matrix

2024-04-18 16:10 UTC, ikstream commented
Hey @Sable-20 I will try to have a look at it. This will take a bit of time, as it is quite a big one, but what I have seen so far looks very good.
Thanks a lot for the work you already put into this rewrite.

2024-04-19 13:16 UTC, Sable-20 commented
> Hey @Sable-20 I will try to have a look at it. This will take a bit of time, as it is quite a big one, but what I have seen so far looks very good. Thanks a lot for the work you already put into this rewrite.

I am aware it's a lot of code, I tried to rewrite in a more modular way that allows for pulling and changing, while it is essentially working there will likely in the future (hopefully near) be minor refactoring to allow separation of modules in a more efficient and organized fashion than currently.

After a few more changes I will update the version to `1.0.0`, these changes will be cleaning up commented out code that is unneeded, optimizations of iterators, documentation of the builder and cleaning up the Nix flakes file. All of which are fairly minor and shouldn't require too extensive of a review after this one!

A contributing file and clippy linters will also be implemented, again, fairly minor changes that should require little to no review.

Thank you for taking the time to read my code, I apologize for how it's a tad bit messy.

2025-03-15 20:24 UTC, pidone requested changes
Hi. First of all, thanks again for your PR and the rewrite in Rust and sorry that it took a while to review. It's pretty cool that the shell completions and manpage are generated automatically. Also that you directly considered docker and nixOS. I'm not really familiar with nixOS so I can't really comment on that part.

I have noted everything that I have noticed. But I would see the following things as essential:
* we should not rename the tool, it should rather function as a drop-in replacment
* The optional parameters are not really optional, because they are directly unwrapped.
* The file structure of the wordlists directory is different in the implementation than in the python version. This could lead to all possible wordlists having to be downloaded again.
* The config is currently being compiled in. This should be loaded at runtime.
* The cli interface should differ as little as possible from the python version.

2025-03-15 20:24 UTC, pidone commented on Dockerfile
> +RUN sed -i 's/reqwest = { version = "\(.*\)", features = \[\(.*\)\] }/reqwest = { version = "\1", default-features = false, features = \["http2", "rustls-tls", \2\] }/' Cargo.toml
Nice workaround. But you can simple add `openssl` and `ca-certificates` and it should work without the native `rusttls`

2025-03-15 20:24 UTC, pidone commented on config/test.toml
> +group = "discovery"
Is there a reason why you choice a list of an large table here? (in rust words a vec of a hashmap).
In my opinion simply a list of tables would be better:
```toml
[[wordlists]]
name = "..."
...

[[wordlists]]
name = "..."
```
and so on.

This is a little bit more inefficient if you only search for a single list by name, but it won't matter here and the data format would be a bit nicer in my opinion.

2025-03-15 20:24 UTC, pidone commented on src/config.rs
> +    let config = toml::from_str::<Config>(include_str!("../config/config.toml"))
This includes the config at compile-time. This means that if you change the config after compiling, it would have no effect, since it has already been baked into the binary. In my opinion, this misses the point of a config. Here the config should be loaded at runtime. Preferably from XDG_CONFIG_HOME. There is also the `dirs` crate that selects the correct config for you depending on the platform.

2025-03-15 20:24 UTC, pidone commented on src/fetch.rs
> +    );
This makes it necessary to specify base-dir as an absolute path. Furthermore, the entire download aborts because the error is not handled in main.
```suggestion
    let file = Path::new(base_dir).join(list.get_name());
    if file.exists() {
        info!("{} already exists -- skipping", list.get_name());
        return Ok(());
    }
```

2025-03-15 20:24 UTC, pidone commented on src/fetch.rs
> +    );
And the python version created subdirectories for the groups. We should keep the file structure as it was.

2025-03-15 20:24 UTC, pidone commented on src/fetch.rs
> +    }
Nice that you even split the download of a file so that it could be distributed to the workers. However, you have to be careful with the order. That's why I would only let the workers download one whole file at a time. And distribute the individual wordlists to the workers.

2025-03-15 20:24 UTC, pidone commented on src/fetch.rs
> +    if re.is_match(list.get_url()) {
You can also use `file.ends_with(".tar.gz")`

2025-03-15 20:24 UTC, pidone commented on src/fetch.rs
> +    let _content = response.text().await?;
Is there a reason why you are reading in the text again?

2025-03-15 20:24 UTC, pidone commented on src/main.rs
> +    );
We should not always create a logfile in the current working dir.

2025-03-15 20:24 UTC, pidone commented on src/main.rs
> +                                                            .collect::<Vec<_>>();
Unwrapping the optional parameters will cause an error if it is not provided.

2025-03-15 20:24 UTC, pidone commented on src/main.rs
> +            match (regex, decompress) {
I don't quite understand the intention behind the match here.

2025-03-15 20:24 UTC, pidone commented on src/main.rs
> +            match (regex, decompress) {
There is also a lot of duplication within the match. We could maybe refactor this part a bit.

2025-03-15 20:24 UTC, pidone commented on src/main.rs
> +                        Red.bold().paint(units::readable_size(lists[i].get_size().ceil() as usize).1.to_string())
This ignores the unit inside of the `repo.toml` and will not return the correct sizes. Either we simple store the size in bytes in the `repo.toml` and always calculate the `readable_size` or you have to check the unit convert it back to bytes and calculate the `readable_size` or just displaying `size` + `unit`

2025-03-15 20:24 UTC, pidone commented on src/main.rs
> +                        size += lst.get_size();
Size is not always just bytes, you should also take `unit` into consideration here

2025-03-15 20:24 UTC, pidone commented on src/main.rs
> +                        size += lst.get_size();
The same for the calculations above.

2025-03-15 20:24 UTC, pidone commented on src/main.rs
> +                            "rwordlistctl/0.1.0",
You should also use `base_dir` and `user_agent` here.

2025-03-15 20:24 UTC, pidone commented on src/main.rs
> +                            "rwordlistctl/0.1.0",
same here

2025-03-15 20:24 UTC, pidone commented on src/repo.rs
> +    }
Is there a particular reason why you are defining getter here and not making the fields public?

2025-03-15 20:24 UTC, pidone commented on src/repo.rs
> +    let repo = toml::from_str::<Repo>(include_str!("../config/repo.toml"))
The same applies here as for the config. The repos are read in once during compilation and are then fixed in the binary. I don't see it as critical with the repo and could also understand the argument that we can only extend the repos using PRs. But we should be aware of this.

2025-03-15 20:24 UTC, pidone commented on src/units.rs
> +pub async fn convert_size(size: u64, unit: Units) -> u64 {
Must this function be async?

2025-03-15 21:05 UTC, ikstream commented
Thanks @pidone for taking the time to review the pull request, much appreciated.

@Sable-20 if you’re still up for it (sorry for the long time I haven’t responded) could you please have a look at the comments?

2026-05-23 15:54 UTC, closed without merging